"""
SQLite database initialization and connection helpers for Jarvis v2 Core.

This module is responsible for:
- Creating the SQLite database file if it does not exist
- Creating the required tables
- Providing a simple helper to get a database connection
"""

from __future__ import annotations

import sqlite3
from pathlib import Path
from typing import Iterator

from ..core.config import get_config
from ..core.logger import get_logger
from ..core.utils import ensure_directory


logger = get_logger(__name__)


def get_database_path() -> Path:
    """
    Return the path to the SQLite database file.
    """
    config = get_config()
    db_path = config.database_path
    ensure_directory(db_path.parent)
    return db_path


def get_connection() -> sqlite3.Connection:
    """
    Get a new SQLite connection.

    Note:
        The connection uses `row_factory=sqlite3.Row` so you can access
        columns by name (e.g. `row["id"]`).
    """
    db_path = get_database_path()
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    return conn


def init_db() -> None:
    """
    Initialize the database by creating all required tables.

    This function is safe to call multiple times; it uses
    `CREATE TABLE IF NOT EXISTS` so existing tables are not dropped.
    """
    logger.info("Initializing SQLite database...")
    db_path = get_database_path()
    logger.info("Using database file at: %s", db_path)

    conn = get_connection()
    try:
        cursor = conn.cursor()

        # Channels being monitored.
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS channels (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                telegram_id INTEGER UNIQUE,
                last_message_id INTEGER,
                username TEXT,
                title TEXT,
                is_active INTEGER NOT NULL DEFAULT 1,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            );
            """
        )

        # Raw messages as collected from Telegram.
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS raw_messages (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                channel_id INTEGER NOT NULL,
                telegram_message_id INTEGER NOT NULL,
                post_link TEXT,
                message_text TEXT NOT NULL,
                message_date TEXT NOT NULL,
                collected_at TEXT NOT NULL,
                content_hash TEXT NOT NULL,
                is_processed INTEGER NOT NULL DEFAULT 0,
                FOREIGN KEY (channel_id) REFERENCES channels (id)
            );
            """
        )

        # Messages after cleaning, deduplication, and (later) analysis.
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS processed_messages (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                raw_message_id INTEGER NOT NULL UNIQUE,
                cleaned_text TEXT NOT NULL,
                short_text TEXT NOT NULL,
                is_duplicate INTEGER NOT NULL DEFAULT 0,
                duplicate_of_raw_message_id INTEGER,
                created_at TEXT NOT NULL,
                classification TEXT,
                importance_score REAL,
                metadata_json TEXT,
                processed_at TEXT NOT NULL,
                included_in_digest INTEGER NOT NULL DEFAULT 0,
                FOREIGN KEY (raw_message_id) REFERENCES raw_messages (id)
            );
            """
        )

        # Daily digests generated by Jarvis.
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS digests (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                digest_date TEXT NOT NULL,
                title TEXT,
                content TEXT NOT NULL,
                created_at TEXT NOT NULL,
                published_to TEXT,
                metadata_json TEXT
            );
            """
        )

        # If the database was created with an older schema, make sure
        # `processed_messages` has the fields we now rely on.
        _ensure_processed_messages_columns(conn)

        conn.commit()
        logger.info("Database initialization complete.")
    finally:
        conn.close()


def _ensure_processed_messages_columns(conn: sqlite3.Connection) -> None:
    """
    Ensure that important columns exist on `processed_messages`.

    This keeps older dev databases compatible when we add new fields.
    """
    cursor = conn.cursor()
    cursor.execute("PRAGMA table_info(processed_messages);")
    columns = {row["name"] for row in cursor.fetchall()}

    def _add_column(name: str, definition: str) -> None:
        if name not in columns:
            cursor.execute(f"ALTER TABLE processed_messages ADD COLUMN {definition};")

    _add_column("short_text", "short_text TEXT NOT NULL DEFAULT ''")
    _add_column("is_duplicate", "is_duplicate INTEGER NOT NULL DEFAULT 0")
    _add_column("duplicate_of_raw_message_id", "duplicate_of_raw_message_id INTEGER")
    _add_column("created_at", "created_at TEXT NOT NULL DEFAULT ''")

